AppBundle\Entity\StockOption:
    type: entity
    table: stock_options
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        company:
            type: string
            length: 100
        ticker_symbol:
            type: string
            length: 5
        quantity:
            type: integer
        value:
            type: decimal
            scale: 2
    oneToMany:
        trades:
            targetEntity: Trade
            mappedBy: stock_option